### ISSUE TITLE
python import from PIL

### ISSUE THREAD

**Issue by nic0dk** [pheuzoune/ha_xiaomi_vacuum_map#2]
Hi, 
to start with, really nice script!

im trying to get it working, but without any luck. i have install AppDaemon via Hass.io addon (running HassOS)
but it seems like my app.yaml that loading your module fail importing needed libs from PIL? have you seen same error before? from the log of AppDaemon:

another question: do i need to fill out xiaomi_vacuum_map_base: ? can i outcommit it, if i don't have any background image?

thanks in advance

```
2019-12-27 11:40:56.870745 WARNING AppDaemon: ------------------------------------------------------------
2019-12-27 11:40:56.871061 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/XiaomiVacuumCleaner.py:
2019-12-27 11:40:56.871208 WARNING AppDaemon: ------------------------------------------------------------
2019-12-27 11:40:56.875032 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/XiaomiVacuumCleaner.py", line 7, in <module>
    from PIL import Image, ImageDraw, ImageChops
ModuleNotFoundError: No module named 'PIL'

2019-12-27 11:40:56.875261 WARNING AppDaemon: ------------------------------------------------------------
2019-12-27 11:40:56.875410 WARNING AppDaemon: Removing associated apps:
2019-12-27 11:40:56.875576 WARNING AppDaemon: XiaomiVacuumCleaner_MapBuilder
```

**Comment by nic0dk** [comment]
alright got a bit clever on this part :) 
for ppl with HassOS on a x86 and installing the AppDaemon addon via Hass.io, you will need following libs and py package:


```
{
  "disable_auto_token": false,
  "system_packages": [
    "libcurl",
    "zlib-dev",
    "libjpeg-turbo-dev",
    "libwebp",
    "tiff",
    "tk",
    "openjpeg",
    "gcc",
    "g++"
  ],
  "python_packages": [
    "pip==19.0.3",
    "Pillow"
  ]
}
```
